name: Public Metrics
on:
  schedule:
    # Runs at minute 0, 20, and 40 of every hour
    - cron: "0,20,40 * * * *" 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ github.token }} 
          user: as000010000
          base: "" 
          plugin_stars: yes
          plugin_stars_limit: 3
          config_allow_authenticated_user_only: no
